### ISSUE TITLE
🆕 : One class day or maybe one week spent on low-level ideas in C

### ISSUE THREAD

**Issue by matt-c-dev** [jameshughes89/cs102#374] opened 2021-11-04 14:53 UTC
### What 
Idea to spend one or two lecture days introducing students to low level functional programming in C, introducing ideas such as pointer arithmetic, what's going on at the lower level when classes are being built

### Why
Help students understand (at a very high level, more concrete stuff can be done in a later course), what is actually happening when they build data structures, index arrays, etc. Without being so complex that they get confused.

**Comment by twentylemon** [comment] 2021-11-04 15:16
Duplicate of #308 #309 #310 #311 #312 #313.

**Comment by jameshughes89** [comment] 2021-11-04 15:17
> Duplicate of #308 #309 #310 #311 #312.

:fire_engine:

**Closed by twentylemon** 2021-11-04 15:16 UTC
Labels: duplicate --- dancers :dancers:

**Comment by matt-c-dev** [comment] 2021-11-04 15:21
> 
> 
> Duplicate of #308 #309 #310 #311 #312.

I did not know that these topics were covered already, good to know.
